name: Create Output File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create output file
      run: echo "Hello, this is a simple output file!" > output.txt

